apiVersion: aws.skycluster.io/v1alpha1
kind: XKube
metadata:
  name: example
  labels:
    skycluster.io/managed-by: "skycluster"
    skycluster.io/provider-platform: aws
    skycluster.io/provider-region: us-east-1
    skycluster.io/provider-zone: us-east-1a
spec: 
  applicationId: example-app
  serviceCidr: 10.0.0.0/24
  podCidr:
    # Overall CIDR block for the pod network.  
    # Must encompass both the public and private subnets below.
    cidr: 10.0.0.0/23  
    # Public subnet (within the above CIDR) used when public IPs are required.
    public: 10.0.0.0/24  
    # Private subnet (within the above CIDR) used when only internal access is needed.
    private: 10.0.1.0/24  

  # Principal ARN for the IAM role that has permissions to manage the cluster
  # The purpose of this role is to allow the user assuming the role to 
  # view the cluster status through the AWS console or CLI (+optional)
  principalArn: arn:aws:iam::123456789012:role/ExampleRole
  nodeGroups:
    - nodeCount: 1
      instanceTypes:
        - t3.medium
      publicAccess: true
      autoScaling:
        enabled: true
        minSize: 1
        maxSize: 3
    - nodeCount: 1
      instanceTypes:
        - t3.medium
      publicAccess: false
      autoScaling:
        enabled: true
        minSize: 1
        maxSize: 3
  providerRef:
    platform: aws
    region: us-east-1
    zones: 
      primary: us-east-1a
      secondary: us-east-1b
    # name: example-provider
status:
  log: "This is a placeholder for the status field"
  # TODO: Fix this
  serviceCidr: "10.10.0.0/24"
  podCidr: "10.10.0.0/24"
  clusterSecretName: example-cluster-secret
  externalClusterName: example-cluster-secret
  controllers:
    - privateIp: 10.135.0.23,
      publicIp: 142.1.174.183,
  providerConfigs: 
    k8s: example-kube-os-scinet-mcwbq
    helm: helm-openstack-scinet-10.135.0.23
  # agents:
  #   - instanceType: m2.xlarge,
  #     publicAccess: true
  #     agent: example-kube-os-scinet-sq56m
  #     providerConfigs: 
  #       ssh: ssh-openstack-scinet-10.135.0.6
  #     ssh: example-kube-os-scinet-6zp55
  #     privateIp: 10.135.0.6
  #     publicIp: 142.1.174.184