apiVersion: skycluster.io/v1alpha1
kind: XSetup
metadata:
  name: mycluster
spec: 
  namespace: skycluster
  publicIp: 142.1.174.178
  submariner:
    enabled: true
# status:
#   namespace: skycluster
#   publicIp: 142.1.174.178
#   providerConfig:
#     helm:
#       name: provider-helm-12345
#     kubernetes:
#       name: provider-kubernetes-67890
#   submariner:
#     enabled: true
#     configMapName: submariner-config