apiVersion: os.skycluster.io/v1alpha1
kind: XSetup
metadata:
  name: example
  labels:
    skycluster.io/managed-by: "skycluster"
    skycluster.io/provider-platform: openstack
    skycluster.io/provider-region: SCINET
    skycluster.io/provider-zone: default
spec:
  vpcCidr: 10.120.0.0/16
  publicKey: |
    ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArD1z...
  gateway:
    image: 2vCPU-4GB
    flavor: TBD
    volumeType: gp2
    volumeSize: 20
    userData : |
      #!/bin/bash
      echo "Initializing gateway..."
  # Subnet CIDRs should be within the VPC CIDR range
  # For Kubernetes cluster we create custom subnets 

  # Note: public (external) networks must be imported and SkyCluster does not support creating them.
  # This is due to SAVI testbed limitation which has a fixed external network
  # and I didn't bother to implement the external network when it cannot be tested.
  
  # To introduce an external network,
  externalNetwork:
    networkName: ext-net 
    networkId: ext-net-id # Required: networkId must be provided here 
    # or as an external object annotations

    subnetName: ext-subnet
    subnetId: ext-subnet-id # Required: subnetId must be provided here 
    # or as an external object annotations

  subnets: # all private subnets
  # The gateway machines will attached to the default subnet, one at least required
    - zone: a
      cidr: 10.120.30.0/24
      gatewayIp: 10.120.30.1
      default: true # [NA]
      # type: private # [NA] public subnet is not supported.

  providerRef:
    platform: gcp
    region: us-east1
    zones: 
      primary: a
      secondary: b

status:
  log: "Setup created successfully."
  externalNetwork:
    networkName: ext-net
    networkId: ext-net-id 
    subnetName: ext-subnet
    subnetId: ext-subnet-id
  keypair:
    name: example-keypair
    id: example-keypair-id
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArD1z...
  vpc:
    id: vpc-12345678
    cidrBlock: "10.20.30.0/16"
  securityGroup:
    id: sg-12345678
  subnets:
    - type: public
      id: subnet-12345678
      networkId: vpc-12345678
      networkName: ext-network
      gatewayIp: 10.20.30.1
      cidrBlock: "10.20.30.0/24"
  gateway:
    publicIp: "<public-ip>"
    privateIp: "<private-ip>"
  router:
    routerName: "<router-name>"
    routerId: "<router-id>"
    externalNetworkId: "id"