apiVersion: skycluster.io/v1alpha1
kind: XKube
metadata:
  name: example
spec: 
  applicationId: example-app
  nodeCidr: 10.0.2.0/24
  serviceCidr: 10.0.0.0/24
  podCidr: 
    cidr: 10.0.1.0/24
    public: ""
    private: ""

  # controlPlane only required for un-managed clusters
  controlPlane:
    deviceNodeName: example-gw-node # required only for baremetal
    instanceType: "8vCPU-32GB"
    autoScaling:
      enabled: true
      minSize: 1
      maxSize: 3
    highAvailability: true

  nodes: # List of device node names for baremetal, only nodes or nodeGroups is required
    - example-node-1

  nodeGroups:
  # There must be at least one node group with public access
  # and it is used for gateway nodes
  - nodeCount: 1
    instanceType: "4vCPU-4GB"
    type: default # default | user-defined only applicable for GCP
    publicAccess: true
    autoScaling: 
      enabled: false
      minSize: 1
      maxSize: 1
    
  - instanceTypes: "2vCPU-4GB"
    publicAccess: false
    autoScaling: 
      enabled: false
      minSize: 1
      maxSize: 1
    
  principal: 
    type: user | role | serviceAccount | servicePrincipal | managedIdentity
    id: string # ARN (AWS) | member (GCP) | principalId (Azure)
    
  providerRef:
    # The provider is identified by the combination 
    # of the provider platform, the region and the primary zone.
    platform: aws
    region: us-east-1
    zones: 
      primary: us-east-1a
      secondary: us-east-1b
status:
  log: "log"
  serviceCidr: "10.0.0.0/24"
  podCidr: "10.0.1.0/24"
  clusterName: "name"
  externalClusterName: "name"
  # Contains kubeconfig
  clusterSecretName: "cluster-secret"
  controllers:
    - privateIp: "privateIp"
      publicIp: "publicIp"
  agents:
    - privateIp: "privateIp"
      publicIp: "publicIp"
      publicAccess: true

