apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tests.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: skycluster.io/v1alpha1
    kind: Test
  mode: Pipeline
  pipeline:
  - step: pull-extra-resources
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: ConfigMap
            apiVersion: v1
            into: CMs
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: skycluster.io/managed-by
                  type: Value
                  value: skycluster
                - key: skycluster.io/script-init
                  type: Value
                  value: ca-certificate
  - step: resources
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: basic
      spec:
        source: /home/ubuntu/skycluster-project/skycluster-compositions/dev/kcl/main.k
  - step: function-auto-ready
    functionRef:
      name: function-auto-ready