apiVersion: gcp.skycluster.io/v1alpha1
kind: XSetup
metadata:
  name: example
  labels:
    skycluster.io/managed-by: "skycluster"
    skycluster.io/provider-platform: gcp
    skycluster.io/provider-region: us-east1
    skycluster.io/provider-zone: b
spec:
  vpcCidr: 10.20.0.0/16
  publicKey: |
    ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArD1z...
  gateway:
    image: TBD
    flavor: TBD
    volumeType: gp2
    volumeSize: 20
    userData : |
      #!/bin/bash
      echo "Initializing gateway..."
  # Subnet CIDRs should be within the VPC CIDR range
  subnets:
    - type: public # not relevant in GCP
      zone: a
      cidr: 10.20.30.0/24
      # deprecated: default: true # only applicatable for GCP
      # # if default is true, the first half of the VPC CIDR will be used for pods, 
      # # the second half for services is divided into two quarters
      # # and the third quarter will be used for services.
      # # the fourth quarter will be used for other resources in the subnet.
      # # Take a look at the composition for more details.
  providerRef:
    platform: gcp
    region: us-east1
    zones: 
      primary: a
      secondary: b
#     name: example-provider
status:
  log: "Setup created successfully."
  podCidr: 10.20.30.0/24
  serviceCidr: 10.20.40.0/24
  keypair:
    name: example-keypair
    id: example-keypair-id
  vpc:
    id: vpc-12345678
    cidrBlock: "10.20.30.0/16"
  subnets:
    - type: public
      id: subnet-12345678
      cidrBlock: "10.20.30.0/24"
  gateway:
    publicIp: "<public-ip>"
    privateIp: "<private-ip>"