apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xk8ses.aws.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: aws.skycluster.io/v1alpha1
    kind: XK8S
  mode: Pipeline
  pipeline:
  - step: extra-resources
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
        - kind: ProviderConfig
          into: ProviderConfigs
          apiVersion: aws.upbound.io/v1beta1
          type: Selector
          selector:
            maxMatch: 1
            minMatch: 1
            matchLabels:
              - key: skycluster.io/managed-by
                type: Value 
                value: skycluster
        - kind: XSetup
          into: SkySetups
          apiVersion: skycluster.io/v1alpha1
          type: Selector
          selector:
            maxMatch: 1
            minMatch: 1
            matchLabels:
              - key: skycluster.io/managed-by
                type: Value 
                value: skycluster
        - kind: XSetup
          into: XSetup
          apiVersion: aws.skycluster.io/v1alpha1
          type: Selector
          selector:
            maxMatch: 1
            minMatch: 1
            matchLabels:
              - key: skycluster.io/managed-by
                type: Value
                value: skycluster
              - key: skycluster.io/provider-platform
                type: Value
                value: aws
              - key: skycluster.io/provider-region
                type: FromCompositeFieldPath
                valueFromFieldPath: spec.providerRef.region
              - key: skycluster.io/provider-zone
                type: FromCompositeFieldPath
                valueFromFieldPath: spec.providerRef.zones.primary
              - key: skycluster.io/application-id
                type: FromCompositeFieldPath
                valueFromFieldPath: spec.applicationId
  - step: resources
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: basic
      spec:
        source: /home/ubuntu/skycluster-project/skycluster-compositions/aws.skycluster.io/apis/xk8ses/kcl/main.k
  - step: function-auto-ready
    functionRef:
      name: function-auto-ready

