apiVersion: gcp.skycluster.io/v1alpha1
kind: XKube
metadata:
  name: example
  labels:
    skycluster.io/managed-by: "skycluster"
    skycluster.io/provider-platform: gcp
    skycluster.io/provider-region: us-east1
    skycluster.io/provider-zone: us-east1-a
spec: 
  applicationId: example-app
  serviceCidr: 10.0.0.0/24
  # Principal ARN for the IAM role that has permissions to manage the cluster
  # The purpose of this role is to allow the user assuming the role to 
  # view the cluster status through the AWS console or CLI (+optional)
  # principalArn: arn:aws:iam::123456789012:role/ExampleRole
  nodeGroups:
    - nodeCount: 1
      instanceType: e2-medium
      publicAccess: true
      autoScaling:
        enabled: true
        minSize: 1
        maxSize: 3
  providerRef:
    platform: gcp
    region: us-east1
    zones: 
      primary: us-east1-a
      # secondary: us-east1-b
    # name: example-provider
status:
  log: "This is a placeholder for the status field"