apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xproviderinstances.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: skycluster.io/v1alpha1
    kind: XProviderInstance
  mode: Pipeline
  pipeline:
  - step: resources
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: basic
      spec:
        source: /home/ubuntu/skycluster-project/skycluster-compositions/skycluster.io/apis/xproviderinstances/kcl/main.k
  - step: function-auto-ready
    functionRef:
      name: function-auto-ready