apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: brokers.submariner.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: submariner.skycluster.io/v1alpha1
    kind: Broker
  mode: Pipeline
  pipeline:
  - step: pull-extra-resources2
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      metadata:
        namespace: submariner-k8s-broker
      spec:
        extraResources:
        - kind: Secret
          into: Secrets
          apiVersion: v1
          type: Selector
          selector:
            minMatch: 0
            maxMatch: 1000
            matchLabels:
              - key: app.kubernetes.io/managed-by
                type: Value 
                value: Helm
  - step: resources
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        annotations:
          "krm.kcl.dev/default_ready": "True"
        name: basic
      spec:
        # dependencies: |
        #   provider-aws = { git = "https://github.com/skycluster-project/kcl-modules", version = "0.0.1" }
        #   helper = { git = "https://github.com/skycluster-project/kcl-modules", version = "0.0.1" }
        source: /home/ubuntu/skycluster-project/skycluster-compositions/submariner.skycluster.io/apis/brokers/kcl/main.k
  - step: function-auto-ready
    functionRef:
      name: function-auto-ready
