apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xkubemeshes.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: skycluster.io/v1alpha1
    kind: XKubeMesh
  mode: Pipeline
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
