apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xoverlays.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: skycluster.io/v1alpha1
    kind: XOverlay
  mode: Pipeline
  pipeline:
  - step: extra-resources
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
        - apiVersion: v1
          kind: Secret
          into: Secrets
          type: Selector
          selector:
            minMatch: 0
            maxMatch: 200
            matchLabels:
              - key: app.kubernetes.io/managed-by
                type: Value 
                value: Helm
        - kind: XSetup
          into: XSetups
          apiVersion: skycluster.io/v1alpha1
          type: Selector
          selector:
            minMatch: 1
            maxMatch: 1
            matchLabels:
              - key: skycluster.io/managed-by
                type: Value 
                value: skycluster
  - step: resources
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: basic
      spec:
        source: /home/ubuntu/skycluster-project/skycluster-compositions/skycluster.io/apis/xoverlays/kcl/main.k
  - step: function-auto-ready
    functionRef:
      name: function-auto-ready