apiVersion: aws.skycluster.io/v1alpha1
kind: XSetup
metadata:
  name: aws-us-east-1
  labels:
    skycluster.io/managed-by: "skycluster"
    skycluster.io/provider-platform: aws
    skycluster.io/provider-region: us-east-1
    skycluster.io/provider-zone: us-east-1a
    # skycluster.io/pause: "true"
spec:
  vpcCidr: 10.20.30.0/16
  gateway:
    flavor: 2vCPU-4GB
    volumeType: gp2
    volumeSize: 8
  # Subnet CIDRs should be within the VPC CIDR range
  subnets:
    - type: public
      zone: us-east-1a
      cidr: 10.20.30.0/24
    - type: private
      zone: us-east-1b
      cidr: 10.20.31.0/24 
  providerRef:
    platform: aws
    region: us-east-1
    zones: 
      primary: us-east-1a
      secondary: us-east-1b
#     name: example-provider
status:
  keypair:
    name: example-keypair
    id: example-keypair-id
  vpc:
    id: vpc-12345678
    cidrBlock: "10.20.30.0/16"
  subnets:
    - type: public
      id: subnet-12345678
      cidrBlock: "10.20.30.0/24"