apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xinstances.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: skycluster.io/v1alpha1
    kind: XInstance
  mode: Pipeline
  pipeline:
    - step: extra-resources
      functionRef:
        name: function-extra-resources
      input:
        apiVersion: extra-resources.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          extraResources:
          - kind: XSetup
            into: XSetups
            apiVersion: skycluster.io/v1alpha1
            type: Selector
            selector:
              minMatch: 1
              maxMatch: 1
              matchLabels:
                - key: skycluster.io/managed-by
                  type: Value
                  value: skycluster
          - kind: XProviderInstance
            into: XProviderInstances
            apiVersion: skycluster.io/v1alpha1
            type: Selector
            selector:
              minMatch: 1
              maxMatch: 10
              matchLabels:
              - key: skycluster.io/managed-by
                type: Value
                value: skycluster
          - kind: ConfigMap
            into: ProviderSettings
            apiVersion: v1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: skycluster.io/provider-platform
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.providerRef.platform
                - key: skycluster.io/provider-region
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.providerRef.region
                - key: skycluster.io/provider-zone
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.providerRef.zone
          - kind: ConfigMap
            into: InitScriptMap
            apiVersion: v1
            type: Selector 
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: skycluster.io/managed-by
                  type: Value 
                  value: skycluster
                - key: skycluster.io/script-type
                  type: Value
                  value: agent-routing-init
          - kind: ConfigMap
            into: InitScriptIpFwMap
            apiVersion: v1
            type: Selector 
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: skycluster.io/managed-by
                  type: Value 
                  value: skycluster
                - key: skycluster.io/script-type
                  type: Value
                  value: agent-ip-forwarding-init
          - kind: ConfigMap
            into: InitScriptRouteMasquerade
            apiVersion: v1
            type: Selector 
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: skycluster.io/managed-by
                  type: Value 
                  value: skycluster
                - key: skycluster.io/script-type
                  type: Value
                  value: agent-routing-init-masquerade
          - kind: ConfigMap
            into: InitScriptNodeExporter
            apiVersion: v1
            type: Selector 
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: skycluster.io/managed-by
                  type: Value 
                  value: skycluster
                - key: skycluster.io/script-type
                  type: Value
                  value: node-exporter
          - kind: ConfigMap
            into: InitScriptHosts
            apiVersion: v1
            type: Selector 
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: skycluster.io/managed-by
                  type: Value 
                  value: skycluster
                - key: skycluster.io/script-type
                  type: Value
                  value: etc-hosts-config
    - step: resources
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        metadata:
          name: basic
        spec:
          dependencies: |
            k8s = "1.32.4"
            provider-kubernetes = { git = "https://github.com/skycluster-project/kcl-modules",version = "0.0.1" }
            provider-helm = { git = "https://github.com/skycluster-project/kcl-modules",version = "0.0.1" }
            helper = { git = "https://github.com/skycluster-project/kcl-modules",version = "0.0.1" }
          source: /home/ubuntu/skycluster-project/skycluster-compositions/skycluster.io/apis/xk8ses/kcl/main.k
    - step: function-auto-ready
      functionRef:
        name: function-auto-ready
