apiVersion: submariner.skycluster.io/v1alpha1
kind: Broker
metadata:
  name: example
  labels:
    skycluster.io/managed-by: skycluster
spec: 
  broker:
    ip: 172.18.0.2
    port: 6443
status:
  broker:
    ca: ""
    token: ""
    url: ""
    psk: ""
  dummy: "ok"