apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xk8ses.skycluster.io
spec:
  compositeTypeRef:
    apiVersion: skycluster.io/v1alpha1
    kind: XK8S
  mode: Pipeline
  pipeline:
  - step: resources
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: basic
      spec:
        dependencies: |
            helper = { git = "https://github.com/skycluster-project/kcl-modules",version = "0.0.1" }
        source: /home/ubuntu/skycluster-project/skycluster-compositions/skycluster.io/apis/xk8ses/kcl/main.k
  - step: function-auto-ready
    functionRef:
      name: function-auto-ready