apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xk8ses.skycluster.io
spec:
  group: skycluster.io
  names:
    categories:
    - crossplane
    kind: XK8S
    plural: xk8ses
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: XK8S is the Schema for the XK8S API.
        properties:
          spec:
            description: XK8SSpec defines the desired state of XK8S.
            properties:
              applicationId:
                type: string
              nodeTypes:
                items:
                  type: string
                type: array
              principal:
                properties:
                  id:
                    type: string
                  type:
                    type: string
                type: object
              providerRef:
                properties:
                  platform:
                    type: string
                  region:
                    type: string
                  zones:
                    properties:
                      primary:
                        type: string
                      secondary:
                        type: string
                    type: object
                type: object
              serviceCidr:
                type: string
            type: object
          status:
            description: XK8SStatus defines the observed state of XK8S.
            properties:
              log:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
